### ISSUE TITLE
Exception during long full GC cycles

### ISSUE THREAD

**Issue by olexandr-ivchenko** [olexandr-ivchenko/btcKillerDatabase#10]
```
org.springframework.web.client.RestClientException: Error while extracting response for type [com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.GenericResponse<com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.Block>] and content type [application/json]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Unexpected end-of-input in VALUE_STRING
 at [Source: (PushbackInputStream); line: 1, column: 875639]; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input in VALUE_STRING
 at [Source: (PushbackInputStream); line: 1, column: 875639]
 at [Source: (PushbackInputStream); line: 1, column: 869602] (through reference chain: com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.GenericResponse["result"]->com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.Block["tx"]->java.util.ArrayList[315]->com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.Tx["vin"]->java.util.ArrayList[5]->com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.Vin["scriptSig"]->com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.ScriptSig["asm"])
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:115) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1000) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:983) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:730) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:684) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:629) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at com.olexandrivchenko.bitcoinkiller.database.inbound.BitcoindServiceImpl.call(BitcoindServiceImpl.java:50) ~[classes/:na]
	at com.olexandrivchenko.bitcoinkiller.database.inbound.BitcoindCallerImpl.getBlock(BitcoindCallerImpl.java:48) ~[classes/:na]
	at com.olexandrivchenko.bitcoinkiller.database.inbound.cache.BitcoindCallerCacheImpl.getBlock(BitcoindCallerCacheImpl.java:47) ~[classes/:na]
	at com.olexandrivchenko.bitcoinkiller.database.main.AppExecutorImpl.loadBlockChain(AppExecutorImpl.java:112) ~[classes/:na]
	at com.olexandrivchenko.bitcoinkiller.database.main.AppExecutorImpl.run(AppExecutorImpl.java:134) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
Caused by: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Unexpected end-of-input in VALUE_STRING
 at [Source: (PushbackInputStream); line: 1, column: 875639]; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input in VALUE_STRING
 at [Source: (PushbackInputStream); line: 1, column: 875639]
 at [Source: (PushbackInputStream); line: 1, column: 869602] (through reference chain: com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.GenericResponse["result"]->com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.Block["tx"]->java.util.ArrayList[315]->com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.Tx["vin"]->java.util.ArrayList[5]->com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.Vin["scriptSig"]->com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.ScriptSig["asm"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:241) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:223) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:100) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	... 17 common frames omitted
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input in VALUE_STRING
 at [Source: (PushbackInputStream); line: 1, column: 875639]
 at [Source: (PushbackInputStream); line: 1, column: 869602] (through reference chain: com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.GenericResponse["result"]->com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.Block["tx"]->java.util.ArrayList[315]->com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.Tx["vin"]->java.util.ArrayList[5]->com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.Vin["scriptSig"]->com.olexandrivchenko.bitcoinkiller.database.inbound.jsonrpc.ScriptSig["asm"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1704) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:371) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:369) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:369) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:369) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:369) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3072) ~[jackson-databind-2.9.5.jar:2.9.5]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:235) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	... 19 common frames omitted
Caused by: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input in VALUE_STRING
 at [Source: (PushbackInputStream); line: 1, column: 875639]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:588) ~[jackson-core-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:565) ~[jackson-core-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMoreGuaranteed(UTF8StreamJsonParser.java:2342) ~[jackson-core-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2427) ~[jackson-core-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2407) ~[jackson-core-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:269) ~[jackson-core-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:35) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.5.jar:2.9.5]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:369) ~[jackson-databind-2.9.5.jar:2.9.5]
	... 41 common frames omitted
```
Generally, full GC will take a lot of time, when 12G of memory allocated, so no point in optimizing GC cycles, just need to make bigger timeout values and add reattempting.

**Comment by olexandr-ivchenko** [comment]
Done
