### ISSUE TITLE
Exception, when trying to load not created block

### ISSUE THREAD

**Issue by olexandr-ivchenko** [olexandr-ivchenko/btcKillerDatabase#15]
During blockchain sync exception is thrown
```
Ehcache stats: added=2011960, removed=1106152, evicted=0, heapSize=1439957kb, elementCount=979336, hitCount=6559926, missCount=4292264, hitRatio=1.53, lastBlock=529468
Last stats: added=1292, removed=1644, evicted=0, heapSize=-1528kb, elementCount=-315, hitCount=8865, missCount=4073, hitRatio=2.18, processedBlocks=1
2018-06-27 16:19:37.360 ERROR 56600 --- [pool-2-thread-1] c.o.b.d.inbound.BitcoindServiceImpl      : Failed to execute daemon call for operation getblockhash and param 529469 
2018-06-27 16:19:42.463 ERROR 56600 --- [pool-2-thread-1] c.o.b.d.inbound.BitcoindServiceImpl      : Failed to execute daemon call for operation getblockhash and param 529469 
Disconnected from the target VM, address: '127.0.0.1:51089', transport: 'socket'
2018-06-27 16:19:47.479 ERROR 56600 --- [pool-2-thread-1] c.o.b.d.inbound.BitcoindServiceImpl      : Failed to execute daemon call for operation getblockhash and param 529469 
2018-06-27 16:19:47.593 ERROR 56600 --- [pool-2-thread-1] c.o.b.database.main.AppExecutorImpl      : Got exception, during blockchain sync

org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:97) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:775) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:728) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:684) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:629) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at com.olexandrivchenko.bitcoinkiller.database.inbound.BitcoindServiceImpl.call(BitcoindServiceImpl.java:59) ~[classes/:na]
	at com.olexandrivchenko.bitcoinkiller.database.inbound.BitcoindCallerImpl.getBlock(BitcoindCallerImpl.java:40) ~[classes/:na]
	at com.olexandrivchenko.bitcoinkiller.database.inbound.cache.BitcoindCallerCacheImpl.getBlock(BitcoindCallerCacheImpl.java:50) ~[classes/:na]
	at com.olexandrivchenko.bitcoinkiller.database.main.AppExecutorImpl.loadBlockChain(AppExecutorImpl.java:78) ~[classes/:na]
	at com.olexandrivchenko.bitcoinkiller.database.main.AppExecutorImpl.run(AppExecutorImpl.java:99) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511) [na:1.8.0_161]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

2018-06-27 16:19:47.630  INFO 56600 --- [       Thread-5] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@434a63ab: startup date [Mon Jun 18 05:18:57 EEST 2018]; root of context hierarchy
2018-06-27 16:19:47.747  INFO 56600 --- [       Thread-5] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-06-27 16:19:47.765  INFO 56600 --- [       Thread-5] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'

Process finished with exit code 1
```
issue is caused by wrong calculation of available for download blocks.

**Comment by olexandr-ivchenko** [comment]
fixed
