### ISSUE TITLE
OutOfMemory when sync database

### ISSUE THREAD

**Issue by olexandr-ivchenko** [olexandr-ivchenko/btcKillerDatabase#5]
```
2018-05-03 17:51:36.679  INFO 74825 --- [pool-3-thread-1] c.o.b.database.main.AppExecutorImpl      : Going to process blocks 154200-154299
```

```
2018-05-03 18:05:39.099  INFO 74825 --- [pool-2-thread-1] c.o.b.d.i.cache.BitcoindCallerCacheImpl  : Added 1897324 transactions, returned from cache 1824461, loaded 1374833
2018-05-03 18:06:40.251  INFO 74825 --- [pool-2-thread-1] c.o.b.d.i.cache.BitcoindCallerCacheImpl  : Added 1897648 transactions, returned from cache 1824766, loaded 1375037
2018-05-03 18:07:13.038  INFO 74825 --- [pool-3-thread-1] c.o.b.database.main.AppExecutorImpl      : Going to save 8619 addresses
2018-05-03 18:07:47.316  INFO 74825 --- [pool-2-thread-1] c.o.b.d.i.cache.BitcoindCallerCacheImpl  : Added 1897859 transactions, returned from cache 1825016, loaded 1375130
2018-05-03 18:09:11.433  INFO 74825 --- [pool-2-thread-1] c.o.b.d.i.cache.BitcoindCallerCacheImpl  : Added 1897859 transactions, returned from cache 1825016, loaded 1375130
2018-05-03 18:10:36.273  INFO 74825 --- [pool-2-thread-1] c.o.b.d.i.cache.BitcoindCallerCacheImpl  : Added 1897859 transactions, returned from cache 1825016, loaded 1375130
2018-05-03 18:11:51.359  INFO 74825 --- [pool-2-thread-1] c.o.b.d.i.cache.BitcoindCallerCacheImpl  : Added 1897859 transactions, returned from cache 1825016, loaded 1375130
2018-05-03 18:16:30.101 ERROR 74825 --- [pool-3-thread-1] c.o.b.database.main.AppExecutorImpl      : Got exception, during blockchain sync

java.lang.OutOfMemoryError: Java heap space
	at org.hibernate.hql.internal.ast.ParameterTranslationsImpl.<init>(ParameterTranslationsImpl.java:129) ~[hibernate-core-5.0.11.Final.jar:5.0.11.Final]
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.getParameterTranslations(QueryTranslatorImpl.java:573) ~[hibernate-core-5.0.11.Final.jar:5.0.11.Final]
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:134) ~[hibernate-core-5.0.11.Final.jar:5.0.11.Final]
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:76) ~[hibernate-core-5.0.11.Final.jar:5.0.11.Final]
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:150) ~[hibernate-core-5.0.11.Final.jar:5.0.11.Final]
	at org.hibernate.internal.AbstractSessionImpl.getHQLQueryPlan(AbstractSessionImpl.java:302) ~[hibernate-core-5.0.11.Final.jar:5.0.11.Final]
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1316) ~[hibernate-core-5.0.11.Final.jar:5.0.11.Final]
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:87) ~[hibernate-core-5.0.11.Final.jar:5.0.11.Final]
	at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:606) ~[hibernate-entitymanager-5.0.11.Final.jar:5.0.11.Final]
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:483) ~[hibernate-entitymanager-5.0.11.Final.jar:5.0.11.Final]
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:121) ~[spring-data-jpa-1.11.0.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:85) ~[spring-data-jpa-1.11.0.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:116) ~[spring-data-jpa-1.11.0.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:106) ~[spring-data-jpa-1.11.0.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:483) ~[spring-data-commons-1.13.0.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:461) ~[spring-data-commons-1.13.0.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.13.0.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$$Lambda$142/1833265449.proceedWithInvocation(Unknown Source) ~[na:na]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[spring-tx-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133) ~[spring-data-jpa-1.11.0.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57) ~[spring-data-commons-1.13.0.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]

2018-05-03 18:16:30.102 ERROR 74825 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.OutOfMemoryError: Java heap space
	at java.lang.StringCoding.encode(StringCoding.java:338) ~[na:1.8.0_161]
	at java.lang.String.getBytes(String.java:918) ~[na:1.8.0_161]
	at ch.qos.logback.core.encoder.LayoutWrappingEncoder.convertToBytes(LayoutWrappingEncoder.java:122) ~[logback-core-1.1.9.jar:na]
	at ch.qos.logback.core.encoder.LayoutWrappingEncoder.doEncode(LayoutWrappingEncoder.java:131) ~[logback-core-1.1.9.jar:na]
	at ch.qos.logback.core.OutputStreamAppender.writeOut(OutputStreamAppender.java:187) ~[logback-core-1.1.9.jar:na]
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:212) ~[logback-core-1.1.9.jar:na]
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:100) ~[logback-core-1.1.9.jar:na]
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84) ~[logback-core-1.1.9.jar:na]
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48) ~[logback-core-1.1.9.jar:na]
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270) ~[logback-classic-1.1.9.jar:na]
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257) ~[logback-classic-1.1.9.jar:na]
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421) ~[logback-classic-1.1.9.jar:na]
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383) ~[logback-classic-1.1.9.jar:na]
	at ch.qos.logback.classic.Logger.info(Logger.java:591) ~[logback-classic-1.1.9.jar:na]
	at com.olexandrivchenko.bitcoinkiller.database.inbound.cache.BitcoindCallerCacheImpl.outputStats(BitcoindCallerCacheImpl.java:77) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
```

Needs to be fixed

**Comment by olexandr-ivchenko** [comment]
Most likely fixed with #8 while migrating to size based eviction on Ehcache 2

**Comment by olexandr-ivchenko** [comment]
The reason for OOM was combination of 
* high memory usage by cache
* way faster calculation vs database operations, so results was waiting in memory to be saved
* Big size of batch result, containing more than 50% addresses with zero balance
* Big queue for database writing
What was done:
* 2G heap cache and -Xmx8G gives enough memory for now. Making more heap cache doesn't looks efficient per below log at 180K blocks
```
Ehcache stats: added=3646606, removed=2858326, *evicted=571299*, heapSize=2094711kb, hitCount=6741052, *missCount=87666*, hitRatio=0.9936750412507626
```
* removing empty addresses, once they identified in calculation thread - more work for calculations, less work for database
* removing empty addresses in database - faster database work
* reducing saving queue to 2 elements - it doesn't make sense to calculate something, that can't be saved, 2 elements should be enough to remove fluctuations. This also dramatically reduces amount of used memory

Tested on parsing blocks 0-190K from scratch - running perfectly fine
```
2018-05-06 20:22:39.363  INFO 26143 --- [pool-3-thread-1] c.o.b.database.main.AppExecutorImpl      : Done blocks 186000-186999 with address count=66834 in 109 seconds
2018-05-06 20:22:39.375  INFO 26143 --- [pool-3-thread-1] c.o.b.database.main.AppExecutorImpl      : Going to process blocks 187000-187999
2018-05-06 20:22:39.959  INFO 26143 --- [pool-2-thread-1] c.o.b.d.outbound.AsyncOutputGateWrapper  : Database job 186000-186999 submited with 66834 addresses
2018-05-06 20:23:15.087  INFO 26143 --- [pool-2-thread-1] c.o.b.database.outbound.OutputGate       : Deleted 21849 zero addresses
2018-05-06 20:23:15.132  INFO 26143 --- [pool-2-thread-1] c.o.b.d.outbound.AsyncOutputGateWrapper  : Updated database with job 186000-186999 address count=66834 in 35173 ms
2018-05-06 20:23:32.601  INFO 26143 --- [pool-2-thread-1] c.o.b.d.i.cache.BitcoindCallerCacheImpl  :  loaded 116671
2018-05-06 20:23:32.601  INFO 26143 --- [pool-2-thread-1] c.o.b.d.i.cache.BitcoindCallerCacheImpl  : 
Ehcache stats: added=4695390, removed=3784425, evicted=687399, heapSize=2095904kb, hitCount=8911966, missCount=116671, hitRatio=1.0722792271776111
```

**Comment by olexandr-ivchenko** [comment]
another tests shown that the issue is still there

**Comment by olexandr-ivchenko** [comment]
fixed
